### ISSUE TITLE
error when launching gazebo.launch

### ISSUE THREAD

**Issue by dineshhops** [lFatality/ros_moveit_gazebo_ws#1]
I am
 roslaunch arm_moveit_config gazebo.launch
... logging to /home/dinesh/.ros/log/8a04524e-cf6e-11eb-a8b7-5b27f7f5f56e/roslaunch-ubuntu-6337.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:33361/

SUMMARY
========

PARAMETERS
 * /arm_controller/gains/joint1/d: 1
 * /arm_controller/gains/joint1/i: 1
 * /arm_controller/gains/joint1/i_clamp: 1
 * /arm_controller/gains/joint1/p: 100
 * /arm_controller/gains/joint2/d: 1
 * /arm_controller/gains/joint2/i: 1
 * /arm_controller/gains/joint2/i_clamp: 1
 * /arm_controller/gains/joint2/p: 100
 * /arm_controller/gains/joint3/d: 1
 * /arm_controller/gains/joint3/i: 1
 * /arm_controller/gains/joint3/i_clamp: 1
 * /arm_controller/gains/joint3/p: 100
 * /arm_controller/gains/joint4/d: 1
 * /arm_controller/gains/joint4/i: 1
 * /arm_controller/gains/joint4/i_clamp: 1
 * /arm_controller/gains/joint4/p: 100
 * /arm_controller/gains/joint5/d: 1
 * /arm_controller/gains/joint5/i: 1
 * /arm_controller/gains/joint5/i_clamp: 1
 * /arm_controller/gains/joint5/p: 100
 * /arm_controller/gains/joint6/d: 1
 * /arm_controller/gains/joint6/i: 1
 * /arm_controller/gains/joint6/i_clamp: 1
 * /arm_controller/gains/joint6/p: 100
 * /arm_controller/joints: ['joint1', 'joint...
 * /arm_controller/type: position_controll...
 * /controller_list: [{'name': 'arm_co...
 * /gazebo/enable_ros_network: True
 * /gazebo_ros_control/pid_gains/joint1/d: 1
 * /gazebo_ros_control/pid_gains/joint1/i: 1
 * /gazebo_ros_control/pid_gains/joint1/p: 100.0
 * /gazebo_ros_control/pid_gains/joint2/d: 1
 * /gazebo_ros_control/pid_gains/joint2/i: 1
 * /gazebo_ros_control/pid_gains/joint2/p: 100.0
 * /gazebo_ros_control/pid_gains/joint3/d: 1
 * /gazebo_ros_control/pid_gains/joint3/i: 1
 * /gazebo_ros_control/pid_gains/joint3/p: 100.0
 * /gazebo_ros_control/pid_gains/joint4/d: 1
 * /gazebo_ros_control/pid_gains/joint4/i: 1
 * /gazebo_ros_control/pid_gains/joint4/p: 100.0
 * /gazebo_ros_control/pid_gains/joint5/d: 1
 * /gazebo_ros_control/pid_gains/joint5/i: 1
 * /gazebo_ros_control/pid_gains/joint5/p: 100.0
 * /gazebo_ros_control/pid_gains/joint6/d: 1
 * /gazebo_ros_control/pid_gains/joint6/i: 1
 * /gazebo_ros_control/pid_gains/joint6/p: 100.0
 * /generic_hw_control_loop/cycle_time_error_threshold: 0.01
 * /generic_hw_control_loop/loop_hz: 300
 * /gripper_controller/gains/f_joint1/d: 1
 * /gripper_controller/gains/f_joint1/i: 1
 * /gripper_controller/gains/f_joint1/i_clamp: 1
 * /gripper_controller/gains/f_joint1/p: 100
 * /gripper_controller/gains/f_joint2/d: 1
 * /gripper_controller/gains/f_joint2/i: 1
 * /gripper_controller/gains/f_joint2/i_clamp: 1
 * /gripper_controller/gains/f_joint2/p: 100
 * /gripper_controller/joints: ['f_joint1', 'f_j...
 * /gripper_controller/type: effort_controller...
 * /hardware_interface/joints: ['joint1', 'joint...
 * /hardware_interface/sim_control_mode: 1
 * /joint_state_controller/publish_rate: 50
 * /joint_state_controller/type: joint_state_contr...
 * /moveit_sim_hw_interface/joint_model_group: arm
 * /moveit_sim_hw_interface/joint_model_group_pose: p1
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.11
 * /use_sim_time: True

NODES
  /
    controller_spawner (controller_manager/spawner)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_gazebo_model (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [6345]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8a04524e-cf6e-11eb-a8b7-5b27f7f5f56e
process[rosout-1]: started with pid [6355]
started core service [/rosout]
process[gazebo-2]: started with pid [6362]
process[gazebo_gui-3]: started with pid [6367]
process[spawn_gazebo_model-4]: started with pid [6371]
process[controller_spawner-5]: started with pid [6373]
process[robot_state_publisher-6]: started with pid [6374]
[ERROR] [1623935924.946556006]: Could not parse visual element for Link [base_link]
[INFO] [1623935925.741595, 0.000000]: Loading model XML from ros parameter robot_description
[INFO] [1623935925.751429, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1623935925.879883, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1623935926.227884801]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1623935926.231468358]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1623935926.363372327]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1623935926.366337806]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1623935927.949292809]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1623935928.079146324, 0.031000000]: Physics dynamic reconfigure ready.
[INFO] [1623935928.173321, 0.106000]: Calling service /gazebo/spawn_urdf_model
Warning [Model.cc:212] Non-unique names detected in XML children of model with name[robot].
[INFO] [1623935928.382253, 0.198000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1623935928.419716089, 0.198000000]: Loading gazebo_ros_control plugin
[ INFO] [1623935928.420281650, 0.198000000]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1623935928.422701262, 0.198000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[ WARN] [1623935928.943537113, 0.198000000]: Replacing previously registered handle 'joint1' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935928.943799576, 0.198000000]: Replacing previously registered handle 'joint1' in 'hardware_interface::PositionJointInterface'.
[ERROR] [1623935928.956269504, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint1/set_parameters]
[ WARN] [1623935929.025353055, 0.198000000]: Replacing previously registered handle 'joint2' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935929.025572695, 0.198000000]: Replacing previously registered handle 'joint2' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935929.026778625, 0.198000000]: Replacing previously registered handle 'joint2' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935929.060263425, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint2/set_parameters]
[ WARN] [1623935929.133840439, 0.198000000]: Replacing previously registered handle 'joint3' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935929.133989325, 0.198000000]: Replacing previously registered handle 'joint3' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935929.134929716, 0.198000000]: Replacing previously registered handle 'joint3' in 'joint_limits_interface::PositionJointSaturationInterface'.
[spawn_gazebo_model-4] process has finished cleanly
log file: /home/dinesh/.ros/log/8a04524e-cf6e-11eb-a8b7-5b27f7f5f56e/spawn_gazebo_model-4*.log
[ERROR] [1623935929.142636212, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint3/set_parameters]
[ WARN] [1623935929.189774463, 0.198000000]: Replacing previously registered handle 'joint4' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935929.190841552, 0.198000000]: Replacing previously registered handle 'joint4' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935929.195096794, 0.198000000]: Replacing previously registered handle 'joint4' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935929.241953575, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint4/set_parameters]
[ WARN] [1623935929.314926676, 0.198000000]: Replacing previously registered handle 'joint5' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935929.315106871, 0.198000000]: Replacing previously registered handle 'joint5' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935929.315872874, 0.198000000]: Replacing previously registered handle 'joint5' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935929.324229311, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint5/set_parameters]
[ WARN] [1623935929.385057704, 0.198000000]: Replacing previously registered handle 'joint6' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935929.385190379, 0.198000000]: Replacing previously registered handle 'joint6' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935929.386005739, 0.198000000]: Replacing previously registered handle 'joint6' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935929.393693538, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint6/set_parameters]
[ WARN] [1623935929.454601439, 0.198000000]: Replacing previously registered handle 'f_joint1' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935929.454795630, 0.198000000]: Replacing previously registered handle 'f_joint1' in 'hardware_interface::EffortJointInterface'.
[ WARN] [1623935929.455709532, 0.198000000]: Replacing previously registered handle 'f_joint1' in 'joint_limits_interface::EffortJointSaturationInterface'.
[ WARN] [1623935929.456000086, 0.198000000]: Replacing previously registered handle 'f_joint2' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935929.456090056, 0.198000000]: Replacing previously registered handle 'f_joint2' in 'hardware_interface::EffortJointInterface'.
[ WARN] [1623935929.456876013, 0.198000000]: Replacing previously registered handle 'f_joint2' in 'joint_limits_interface::EffortJointSaturationInterface'.
[ INFO] [1623935929.471848346, 0.198000000]: Loaded gazebo_ros_control.
[ INFO] [1623935929.472118948, 0.198000000]: Loading gazebo_ros_control plugin
[ INFO] [1623935929.472237773, 0.198000000]: Starting gazebo_ros_control plugin in namespace: /
[INFO] [1623935929.513574, 0.198000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1623935929.520683, 0.198000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1623935929.526600, 0.198000]: Loading controller: arm_controller
[ERROR] [1623935929.612819022, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint1/set_parameters]
[INFO] [1623935929.681430, 0.198000]: Loading controller: gripper_controller
[ERROR] [1623935929.720896453, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint2/set_parameters]
[ERROR] [1623935929.797974480, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint3/set_parameters]
[ERROR] [1623935929.887599586, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint4/set_parameters]
[INFO] [1623935929.947199, 0.198000]: Loading controller: joint_state_controller
[INFO] [1623935929.972684, 0.198000]: Controller Spawner: Loaded controllers: arm_controller, gripper_controller, joint_state_controller
[ERROR] [1623935930.018782895, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint5/set_parameters]
[ERROR] [1623935930.066433036, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint6/set_parameters]
[ WARN] [1623935930.125667668, 0.198000000]: Replacing previously registered handle 'joint1' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935930.125754450, 0.198000000]: Replacing previously registered handle 'joint1' in 'hardware_interface::PositionJointInterface'.
[ERROR] [1623935930.142558610, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint1/set_parameters]
[ WARN] [1623935930.181221704, 0.198000000]: Replacing previously registered handle 'joint2' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935930.181303838, 0.198000000]: Replacing previously registered handle 'joint2' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935930.182053702, 0.198000000]: Replacing previously registered handle 'joint2' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935930.219614098, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint2/set_parameters]
[ WARN] [1623935930.271279760, 0.198000000]: Replacing previously registered handle 'joint3' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935930.271377936, 0.198000000]: Replacing previously registered handle 'joint3' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935930.273245192, 0.198000000]: Replacing previously registered handle 'joint3' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935930.298180226, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint3/set_parameters]
[ WARN] [1623935930.357230213, 0.198000000]: Replacing previously registered handle 'joint4' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935930.357312687, 0.198000000]: Replacing previously registered handle 'joint4' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935930.360496582, 0.198000000]: Replacing previously registered handle 'joint4' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935930.399338652, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint4/set_parameters]
[ WARN] [1623935930.454272123, 0.198000000]: Replacing previously registered handle 'joint5' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935930.454452863, 0.198000000]: Replacing previously registered handle 'joint5' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935930.459611094, 0.198000000]: Replacing previously registered handle 'joint5' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935930.493359595, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint5/set_parameters]
[ WARN] [1623935930.554479509, 0.198000000]: Replacing previously registered handle 'joint6' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935930.554680306, 0.198000000]: Replacing previously registered handle 'joint6' in 'hardware_interface::PositionJointInterface'.
[ WARN] [1623935930.555710476, 0.198000000]: Replacing previously registered handle 'joint6' in 'joint_limits_interface::PositionJointSaturationInterface'.
[ERROR] [1623935930.570290375, 0.198000000]: Tried to advertise a service that is already advertised in this node [/gazebo_ros_control/pid_gains/joint6/set_parameters]
[ WARN] [1623935930.649880866, 0.198000000]: Replacing previously registered handle 'f_joint1' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935930.650021544, 0.198000000]: Replacing previously registered handle 'f_joint1' in 'hardware_interface::EffortJointInterface'.
[ WARN] [1623935930.651899242, 0.198000000]: Replacing previously registered handle 'f_joint1' in 'joint_limits_interface::EffortJointSaturationInterface'.
[ WARN] [1623935930.652048424, 0.198000000]: Replacing previously registered handle 'f_joint2' in 'hardware_interface::JointStateInterface'.
[ WARN] [1623935930.652114793, 0.198000000]: Replacing previously registered handle 'f_joint2' in 'hardware_interface::EffortJointInterface'.
[ WARN] [1623935930.653533735, 0.198000000]: Replacing previously registered handle 'f_joint2' in 'joint_limits_interface::EffortJointSaturationInterface'.
[ERROR] [1623935930.654674068, 0.198000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/list_controllers]
[ERROR] [1623935930.654941535, 0.198000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/list_controller_types]
[ERROR] [1623935930.655025797, 0.198000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/load_controller]
[ERROR] [1623935930.655048192, 0.198000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/unload_controller]
[ERROR] [1623935930.655063984, 0.198000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/switch_controller]
[ERROR] [1623935930.655079604, 0.198000000]: Tried to advertise a service that is already advertised in this node [/controller_manager/reload_controller_libraries]
[ INFO] [1623935930.655175359, 0.198000000]: Loaded gazebo_ros_control.
[INFO] [1623935930.656782, 0.199000]: Started controllers: arm_controller, gripper_controller, joint_state_controller
context mismatch in svga_surface_destroy
context mismatch in svga_surface_destroy

You have make this tutorial easy with step by step guidance, however i am new on ros.
I am trying to execute the gazebo.launch as mentioned in tutorial but facing this issue, please help to solve.
Thankyou in advance.

**Comment by dineshhops** [comment]
You have make this tutorial easy with step by step guidance, however i am new on ros.
I am trying to execute the gazebo.launch as mentioned in tutorial but facing this issue, please help to solve.
Thankyou in advance.

**Comment by lFatality** [comment]
@dineshhops Did you make any changes to the code? I cloned the repo again and executed the code and it worked as expected for me. 

The steps I took are:
```
git clone https://github.com/lFatality/ros_moveit_gazebo_ws.git
cd ros_moveit_gazebo_ws/
catkin_make
source devel/setup.bash
roslaunch arm_moveit_config gazebo.launch
```

**Comment by dineshhops** [comment]
I followed the same steps and issue get solved. I was trying to follow video tutorial in first place, I must have made some mistake somewhere. I will work on that. But your model works perfectly. Thanks.
